spring.application.name=LedgerCore

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:ledgercore}
spring.datasource.username=${POSTGRES_USER:ledgercore}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
